// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {ERC4626Extern, BaseRainlangExtern} from "../abstract/ERC4626Extern.sol";
import {ERC4626SubParser, BaseRainlangSubParser} from "../abstract/ERC4626SubParser.sol";
import {IDescribedByMetaV1} from "rain-metadata-0.1.0/src/interface/IDescribedByMetaV1.sol";
import {DESCRIBED_BY_META_HASH} from "../generated/ERC4626Words.pointers.sol";

contract ERC4626Words is ERC4626Extern, ERC4626SubParser {
    /// @inheritdoc IDescribedByMetaV1
    /// @return keccak256 of the CBOR-wrapped authoring metadata for the two ERC-4626
    /// conversion words, generated by `script/build.sh` and pinned in
    /// `src/generated/ERC4626Words.pointers.sol`.
    function describedByMetaV1() external pure returns (bytes32) {
        return DESCRIBED_BY_META_HASH;
    }

    /// This is only needed because the parser and extern base contracts both
    /// implement IERC165, and the compiler needs to be told how to resolve the
    /// ambiguity.
    /// @inheritdoc BaseRainlangSubParser
    /// @param interfaceId The ERC-165 interface identifier to query.
    /// @return True if this contract implements the queried interface.
    function supportsInterface(bytes4 interfaceId)
        public
        view
        virtual
        override(BaseRainlangSubParser, BaseRainlangExtern)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
